### PR TITLE
Sandbox: bump Calabash iOS version to 0.17

### PR DESCRIPTION
**Pull request by jmoody**
Calabash iOS 0.17 is out.

### CODE REVIEW

**Comment by sapieneptus** [comment]
@jmoody Unfortunately, the deploy process for updating gems is fairly complex:

1) Update the ad-hoc gemfile
2) Update the travis tests
3) Update the CalabashGems.zip in s3

This is why I propose we include some sort of upgrade tool inside of the sandbox.

**Comment by jmoody** [comment]
Right right.  I forgot about that step.

**Comment by jmoody** [comment]
You are keeper of the S3 keys, no?  Can you take control of this PR? If not assign back to me and pass me the credentials.

**Comment by sapieneptus** [comment]
I think we might have to ignore CI on this one. It's not going to work until the new CalabashGems.zip is in S3

**Pull request merged**
