### PR TITLE
Rm old install scripts, update README

### PR DESCRIPTION
**Pull request by sapieneptus**
CC: @jmoody @topgenorth

### CODE REVIEW

**Comment by jmoody** [comment]
I am happy with this _as is_, but I would like it to be shorter.

1. I want room for Windows instructions.
2. Shorter READMEs are better.

Move some of the README content to a Wiki page #35

I think that removing the script could have been done outside this PR and done without a PR.

**Comment by topgenorth** [comment]
FYI, this PR has broken some of the links in http://developer.xamarin.com/guides/testcloud/calabash/configuring/.

**Comment by sapieneptus** [comment]
@topgenorth Oh, I guess we had assumed the sandbox documentation had already gone live - how far off is that? Would it be worth reverting this?

**Comment by topgenorth** [comment]
No it hadn't - I was waiting for word from you guys to tell me. I pushed the docs for the OS X sandbox, however I don't have anything for Windows yet. I'm assuming the Powershell script is good to go and will add that to my TODO list.

**Pull request merged**
