### PR TITLE
Basic windows install instructions

### PR DESCRIPTION
**Pull request by sapieneptus**
CC: @jonstoneman @jmoody

### CODE REVIEW

**Comment by jonstoneman** [comment]
I've created PR https://github.com/calabash/install/pull/31 to bring my scripts into this branch.  The path in `SANDBOX.README.md` can then be updated.

`README.md` should also be updated, or possibly `SANBOX.README.md` should just replace it?

Presumably the instruction about the Android SDK and ANDROID_HOME need to be in SANDBOX.README.md?

**Comment by jmoody** [comment]
> README.md should also be updated, or possibly SANBOX.README.md should just replace it?

+ 1 for replacing.

**Comment by sapieneptus** [comment]
@jmoody 
> 1 for replacing.
+ 1 or - 1 ?

**Comment by jmoody** [comment]
:+1:

**Comment by jmoody** [comment]
@jonstoneman I think merge #31 first and then we we go about updating the docs.

This will have to be coordinated with the docs team.

**Comment by sapieneptus** [comment]
@jonstoneman Please review README.md and let me know if it has your blessing

**Comment by jonstoneman** [comment]
README.md looks good to me :)

**Comment by sapieneptus** [comment]
@jonstoneman howsabout now?

**Comment by jonstoneman** [comment]
The delete looks fine but it needs to download/execute the install script command afterwards.

You should also remove `(OSX Only)` from the title.  :)

**Pull request merged**
