### PR TITLE
Improve the MacOS install script

### PR DESCRIPTION
**Pull request by jmoody**
**REBASED** Sat Nov 23 14:00 CET

### Motivation

Progress on: 

* **Fix the install path in .calabash** #3  - TL;DR - don't delete the ~/.calabash directory.  That needs to be preserved because we'll be writing things there.
* **repo needs CI** #7

The script needed some TLC.  There is a lot of room for improvement, but this is a good first step.

- [x] Travis CI; unit tests vs. rvm environment
- [x] Jenkins CI; unit vs. rbenv environment

Integration tests are failing on Jenkins.

* OSX script is not working with MacOS system ruby #14

### CODE REVIEW

**Comment by jmoody** [comment]
Tested on MacOS system ruby.  It works locally.

There is a lot of risk in pushing this to master because it will be instantly available via the links in the Xamarin docs.  Maybe this should be a git-flow repo?

@krukow

**Comment by TobiasRoikjer** [comment]
@jmoody @krukow  @topgenorth  I would still recommend we installed using bundler.

We can install bundler using this command
```shell
# If the user does not have bundler (installs as non-root on default OSX ruby)
gem install --user-install bundler
export PATH=$PATH:~/.gem/ruby/[rubyversion]/bin
bundle init
echo "calabash" >> Gemfile
echo "cucumber" >> Gemfile
bundle install --path ./calabash-gems
```

**Comment by jmoody** [comment]
> # If the user does not have bundler (installs as non-root on default OSX ruby)
gem install --user-install bundler

That requires _sudo_ by default on MacOS?

**Comment by jmoody** [comment]
We've got a problem.

**Cannot install calabash-android with MacOS system ruby or any ruby 2.0: cannot build json 1.8.3 native extensions** [#643](https://github.com/calabash/calabash-android/issues/643)


I've reproduced on a couple of different machines.

**Comment by jmoody** [comment]
@krukow Is there a reason for the fork here?

https://github.com/calabash/install/blob/master/install-calabash-local-osx.rb#L36

**Comment by krukow** [comment]
@jmoody no it looks like an artefact of an older version

**Comment by jmoody** [comment]
It is not possible to run integration tests (cucumber + test cloud submit) on Travis because there is no system ruby (/usr/bin/ruby).

**Comment by jmoody** [comment]
Jenkins test this please

**Comment by jmoody** [comment]
I am going to merge this despite the Jenkins integration tests not passing.

I am beginning to suspect that this script can _install_ gems, but the gems cannot be used to run Calabash tests.

**Pull request merged**
